"""对话端口：状态提交与外部执行分离。返回值是数据，不暴露 SQL 游标。"""
from typing import Protocol, Any


class ConversationRepository(Protocol):
    def turn(self, run_id: str) -> dict: ...
    def session(self, session_id: str) -> dict: ...
    def begin_step(self, run_id: str) -> dict | None: ...
    def bind(self, run_id: str, step: int, decision_id: str, decision: Any) -> None: ...
    def record_route_fallback(self, run_id: str, step: int, route: str, reason: str) -> None: ...
    def finish_tool(self, run_id: str, step: int, result: dict) -> None: ...
    def reject(self, run_id: str, step: int, reason: str) -> None: ...
    def finish_reply(self, run_id: str, step: int, text: str, question_id: str | None = None) -> None: ...
    def block(self, run_id: str, status: str, reason: str) -> None: ...
    def reopen(self, run_id: str) -> None: ...


class ConversationExecution(Protocol):
    def lock(self, run_id: str) -> Any: ...
    def recover(self, run_id: str) -> bool: ...
    def decide(self, turn: dict, step: int, provider: Any) -> tuple: ...
    def execute(self, turn: dict, decision_id: str, decision: Any) -> dict: ...
