"""六边形端口：应用层只依赖用例合同，不持有 SQL 游标或具体供应商。

Repository 拥有原子状态提交；Execution 拥有受管 I/O 与对账。
Model 决策以 step key 去重，未知调用不可重新派发。
"""
from __future__ import annotations
from typing import Any, Protocol
from .models import StepDecision


class AgentRepository(Protocol):
    def create(self, spec: dict[str, Any], manifest: dict[str, Any]) -> str: ...
    def row(self, run_id: str) -> dict[str, Any]: ...
    def notes(self, run_id: str) -> list[dict[str, Any]]: ...
    def manifest(self, run_id: str) -> dict[str, Any]: ...
    def begin_step(self, run_id: str) -> dict[str, Any] | None: ...
    def bind_decision(self, run_id: str, step: int, decision_id: str, decision: StepDecision) -> None: ...
    def finish_step(self, run_id: str, step: int, kind: str, payload: dict[str, Any], status: str = "RUNNING") -> None: ...
    def block(self, run_id: str, status: str, reason: str) -> None: ...
    def reopen(self, run_id: str) -> None: ...
    def answer(self, run_id: str, question_id: str, text: str) -> None: ...
    def cancel(self, run_id: str) -> None: ...
    def verify_and_deliver(self, run_id: str, step: int, verdict: str, reason: str,
                           decision: StepDecision, candidate: dict[str, str]) -> None: ...
    def status(self, run_id: str) -> dict[str, Any]: ...


class AgentExecution(Protocol):
    def lock(self, run_id: str) -> Any: ...
    def request_decision(self, run_id: str, step: int, provider: Any, context: str) -> tuple[str, StepDecision]: ...
    def execute(self, run_id: str, decision_id: str, decision: StepDecision) -> dict[str, Any]: ...
    def recover(self, run_id: str) -> bool: ...
    def current(self, run_id: str) -> dict[str, str]: ...
    def evidence(self, run_id: str) -> dict[str, dict[str, Any]]: ...
